create table if not exists public.game_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  game_key text not null,
  score numeric not null check (score >= 0),
  score_label text,
  created_at timestamptz not null default now()
);

create index if not exists game_scores_user_game_score_idx
  on public.game_scores (user_id, game_key, score desc, created_at desc);

alter table public.game_scores enable row level security;

grant select, insert on table public.game_scores to authenticated;
grant usage, select on sequence public.game_scores_id_seq to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'game_scores'
      and policyname = 'Users can read own scores'
  ) then
    create policy "Users can read own scores"
      on public.game_scores
      for select
      to authenticated
      using (auth.uid() = user_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'game_scores'
      and policyname = 'Users can insert own scores'
  ) then
    create policy "Users can insert own scores"
      on public.game_scores
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;
end
$$;

create or replace view public.my_game_high_scores
with (security_invoker = true) as
select
  game_key,
  max(score) as high_score,
  count(*) as attempts,
  max(created_at) as last_played_at
from public.game_scores
where user_id = auth.uid()
group by game_key;

grant select on table public.my_game_high_scores to authenticated;
